"""Build an idempotent Supabase import from the supplied recap workbook."""

import sys
from pathlib import Path

from openpyxl import load_workbook


def sql(value):
    if value is None or value == "" or value == "-":
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).strip().replace("'", "''") + "'"


def rows(sheet):
    return [tuple(cell.value for cell in row) for row in sheet.iter_rows(min_row=5)
            if isinstance(row[0].value, int) and isinstance(row[1].value, str)]


def reclamation(data, table, period_col):
    values = []
    for row in data:
        _, name, period, document, sk, plan, guarantee, bank_deposit, status, note = row
        deposit = bank = None
        if isinstance(bank_deposit, str) and bank_deposit.strip() != "-":
            if ";" in bank_deposit:
                deposit = bank_deposit.strip()
            else:
                parts = bank_deposit.split("/", 1)
                deposit = parts[0].strip()
                bank = parts[1].strip() if len(parts) > 1 else None
        remarks = "; ".join(str(v).strip() for v in (status, note) if v)
        fields = (name, period, document, sk, plan, deposit, bank, guarantee, remarks)
        values.append("  (" + ", ".join(map(sql, fields)) + ")")
    cols = f"pemegang_iup, {period_col}, dokumen, no_sk_pengesahan, jumlah_rencana, no_deposito, nama_bank, jumlah_jaminan, keterangan"
    return f"""-- {table}: {len(values)} source records; skip a company already represented in this module.
WITH source ({cols}) AS (VALUES
{',\n'.join(values)}
)
INSERT INTO public.{table} ({cols})
SELECT {cols} FROM source s
WHERE NOT EXISTS (
  SELECT 1 FROM public.{table} d
  WHERE upper(regexp_replace(d.pemegang_iup, '[^A-Za-z0-9]', '', 'g')) =
        upper(regexp_replace(s.pemegang_iup, '[^A-Za-z0-9]', '', 'g'))
);
"""


def pascatambang(data):
    values = ["  (" + ", ".join(map(sql, (r[1], r[2], r[3], r[4], r[5]))) + ")"
              for r in data]
    cols = "pemegang_iup, no_sk_pengesahan, jumlah_rencana, jumlah_jaminan, status_jaminan"
    return f"""-- Pascatambang: {len(values)} source records.
WITH source ({cols}) AS (VALUES
{',\n'.join(values)}
)
INSERT INTO public.pascatambang ({cols})
SELECT {cols} FROM source s
WHERE NOT EXISTS (
  SELECT 1 FROM public.pascatambang d
  WHERE upper(regexp_replace(d.pemegang_iup, '[^A-Za-z0-9]', '', 'g')) =
        upper(regexp_replace(s.pemegang_iup, '[^A-Za-z0-9]', '', 'g'))
);
"""


def main(source, destination):
    workbook = load_workbook(source, read_only=True, data_only=True)
    eks = rows(workbook["Ringkasan - Eksplorasi"])
    op = rows(workbook["Ringkasan - Operasi Produksi"])
    pasca = rows(workbook["Pascatambang"])
    assert (len(eks), len(op), len(pasca)) == (56, 21, 21)
    header = """-- Generated from Rekap_Kewajiban_Reklamasi_Aceh1.xlsx.
-- Run once in Supabase SQL Editor. Safe to rerun: existing companies are skipped.
-- Existing rows are never updated or deleted. Review counts after running.
-- Exploration summary at workbook bottom reverses its detailed status totals;
-- this import uses the 56 detailed records (21 placed, 35 not placed).
BEGIN;
CREATE TABLE IF NOT EXISTS public.pascatambang (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pemegang_iup text NOT NULL,
  no_sk_pengesahan text,
  jumlah_rencana numeric,
  jumlah_jaminan numeric,
  status_jaminan text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS pascatambang_pemegang_idx ON public.pascatambang (pemegang_iup);
ALTER TABLE public.pascatambang ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS read_public ON public.pascatambang;
DROP POLICY IF EXISTS write_admin ON public.pascatambang;
CREATE POLICY read_public ON public.pascatambang FOR SELECT USING (true);
CREATE POLICY write_admin ON public.pascatambang FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT SELECT ON public.pascatambang TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.pascatambang TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.pascatambang_id_seq TO authenticated;

"""
    footer = "\nCOMMIT;\n"
    text = header + reclamation(eks, "reklamasi_eks", "tahun") + reclamation(op, "reklamasi_op", "periode_ke") + pascatambang(pasca) + footer
    Path(destination).write_text(text, encoding="utf-8")
    print(f"Prepared SQL: {len(eks)} exploration, {len(op)} operation, {len(pasca)} post-mining records")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
