-- Generated from Rekap_Kewajiban_Reklamasi_Aceh1.xlsx.
-- Run once in Supabase SQL Editor. Safe to rerun: existing companies are skipped.
-- Existing rows are never updated or deleted. Review counts after running.
-- Exploration summary at workbook bottom reverses its detailed status totals;
-- this import uses the 56 detailed records (21 placed, 35 not placed).
BEGIN;
CREATE TABLE IF NOT EXISTS public.pascatambang (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pemegang_iup text NOT NULL,
  no_sk_pengesahan text,
  jumlah_rencana numeric,
  jumlah_jaminan numeric,
  status_jaminan text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS pascatambang_pemegang_idx ON public.pascatambang (pemegang_iup);
ALTER TABLE public.pascatambang ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS read_public ON public.pascatambang;
DROP POLICY IF EXISTS write_admin ON public.pascatambang;
CREATE POLICY read_public ON public.pascatambang FOR SELECT USING (true);
CREATE POLICY write_admin ON public.pascatambang FOR ALL TO authenticated USING (true) WITH CHECK (true);
GRANT SELECT ON public.pascatambang TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.pascatambang TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.pascatambang_id_seq TO authenticated;

-- reklamasi_eks: 56 source records; skip a company already represented in this module.
WITH source (pemegang_iup, tahun, dokumen, no_sk_pengesahan, jumlah_rencana, no_deposito, nama_bank, jumlah_jaminan, keterangan) AS (VALUES
  ('CV. BLANG LEUMAK RAYA', '2024-2028', 'Ada', '500.10.29.16/118', 326700000, 'AA 67950', 'Bank Aceh', 326700000, 'Sudah menempatkan jaminan'),
  ('PT. ABDYA MINERAL PRIMA', '2025-2029', 'Ada', '500.10.29.16/524', 17520000, 'AA 78258', 'BANK ACEH', 17520000, 'Sudah menempatkan jaminan'),
  ('PT. ACEH BUMOE PUSAKA', '2024-2028', 'Ada', '500.10.29.16/670', 70155000, 'AA 78263', 'BANK ACEH', 70155000, 'Sudah menempatkan jaminan'),
  ('PT. ACEH JAYA ALAM MINERAL', '2024-2028', 'Ada', '500.10.29.16/523', 76492000, 'AA 78260', 'BANK ACEH', 76492000, 'Sudah menempatkan jaminan'),
  ('PT. ACEH JAYA ANDALAN NUSANTARA', '2024-2028', 'Ada', '500.10.29.16/522', 16530000, 'AA 78255', 'BANK ACEH', 16530000, 'Sudah menempatkan jaminan'),
  ('PT. ACEH JAYA BARU UTAMA', '2025-2029', 'Ada', '500.10.29.16/521', 878161000, 'AA 78259', 'BANK ACEH', 878161000, 'Sudah menempatkan jaminan'),
  ('PT. ACSEL MAKMUR ALAM', '2024-2028', 'Ada', '500.10.29.16/526', 16530000, 'AA 78256', 'BANK ACEH', 16530000, 'Sudah menempatkan jaminan'),
  ('PT. ADIKARA REKSA MITRA', '2025-2029', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Progres Revisi Dokumen'),
  ('PT. ALAM CEMPAKA WANGI', '2026-2030', 'Ada', '500.10.29.16/686', 238550000, 'AA 78262', 'BANK ACEH', 238550000, 'Sudah menempatkan jaminan'),
  ('PT. ALEXA TAMBANG ABADI', '2024-2028', 'Ada', '500.10.29.16/435', 82627000, NULL, NULL, 82627000, 'Belum Menempatkan Jaminan; Sudah Persetujuan namun belum menempatkan jaminan.'),
  ('PT. ARITA ACEH SEJAHTERA', '2022-2026', 'Ada', '500.10.29.16/525', 403776000, 'AA 78257', 'BANK ACEH', 403776000, 'Sudah menempatkan jaminan'),
  ('PT. ATHENA TAMBANG JAYA', '2024-2028', 'Ada', '500.10.29.16/228', 194875000, 'AA 78244', 'Bank Aceh', 194875000, 'Sudah menempatkan jaminan'),
  ('PT. AURUM INDO MINERAL', '2025-2029', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. BERSAMA SUKSES MINING', '2024-2028', 'Ada', '500.10.29.16/229', 157612824, 'AA 67953', 'Bank Aceh', 157612824, 'Sudah menempatkan jaminan'),
  ('PT. BRAVO ENERGI SENTOSA', '2025-2029', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Progres Revisi Dokumen'),
  ('PT. BUKIT MINERAL ABADI', '2026-2030', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. BUMI MULYA ENERGI', '2025-2029', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. DAR CAHAYA ACEH MAKMUR', '2026-2030', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. DRABA MINERAL INTERNASIONAL', '2022-2026', 'Ada', '500.10.29.16/1529', 84108050, NULL, NULL, 84108050, 'Belum Menempatkan Jaminan; Sudah Persetujuan namun belum menempatkan jaminan.'),
  ('PT. HIKMAH BEUTONG RAYA', '2026-2030', 'Ada', '500.10.29.16/554', 98222400, 'AA 78253', 'Bank Aceh', 98222400, 'Sudah menempatkan jaminan'),
  ('PT. KARYA BUDIDAYA NUSANTARA', '2025-2029', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Progres Revisi Dokumen'),
  ('PT. KINSTON ABADI ENERGY', '2026-2030', 'Ada', '500.10.29.16/182', 180569000, 'AA 78238', 'BANK ACEH', 180569000, 'Sudah menempatkan jaminan'),
  ('PT. KINSTON ABADI MINERAL', '2026-2030', 'Ada', '500.10.29.16/181', 616692000, 'AA 78237', 'BANK ACEH', 616692000, 'Sudah menempatkan jaminan'),
  ('PT. LONGSUNINDO PERKASA', '2022-2026', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. MAS PUTIH ANEKA TAMBANG', '2022-2026', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. MINERAL AGAM PRIMA', '2022 - 2030', 'Ada', '500.10.29.16/502 & 21 April 2025', 113071000, 'AA 78065', 'BANK ACEH', 113071000, 'Sudah menempatkan jaminan'),
  ('PT. MINERAL MEGA SENTOSA', '2026-2030', 'Ada', '500.10.29.16/676', 237688000, 'AA 67957', 'BANK ACEH', 237688000, 'Sudah menempatkan jaminan'),
  ('PT. MOZIKA KARIAN MEUTUAH', '2026-2030', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Progres Evaluasi'),
  ('PT. ONETAMA KENCANA ENERGI', '2025-2029', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Progres Revisi Dokumen'),
  ('PT. RAIN TAMBANG BERSAUDARA', '2025-2029', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Progres Persetujuan'),
  ('PT. RINDANG JAYA RESOURCES', '2022-2026', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. SAMASAMA PRABA DENTA', '2024-2028', 'Ada', '500.10.29.16/1308', 328241650, 'AA 78168', 'Bank Aceh', 328241650, 'Sudah menempatkan jaminan'),
  ('PT. SELATAN ACEH EMAS', '2022-2026', 'Ada', '500.10.29.16/131', 311800000, 'AA 67949', 'Bank Aceh', 311800000, 'Sudah menempatkan jaminan'),
  ('PT. SERAMBI TIMUR RESOURCES', '2025-2029', 'Ada', '500.10.29.16/453', 318620000, 'AA 78035 dan AA 78252', 'Bank Aceh', 318620000, 'Sudah menempatkan jaminan'),
  ('PT. SINGKIL BARA UTAMA', '2024-2028', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. SUKSES ENERGI SAKTI', '2026-2030', 'Ada', '500.10.29.16/671', 380396000, 'AB 00062553', 'BSI', 380396000, 'Sudah menempatkan jaminan'),
  ('PT. SULTAN MAJU BERSAMA', '2022-2026', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Progres Revisi Dokumen'),
  ('PT. SUMBER BERKAH ENERGI', '2025-2029', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. SUMBER ENERGI SANGGABERU', '2025-2029', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. SURYA BARA MENTARI', '2026-2030', 'Ada', '500.10.29.16/671', 175263000, 'A 00062555', 'BANK ACEH', 175263000, 'Sudah menempatkan jaminan'),
  ('PT. TAMBANG ALAM BERSAUDARA', '2022-2026', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Progres Revisi Dokumen'),
  ('PT. TUNAS MANDIRI PERSADA', '2025-2029', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. UNIVERSAL PRATAMA SEJAHTERA', '2021-2025', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. WAHANA PRIMA INVESTINDO', '2026-2030', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. HASIL BUMI SEMBADA', '2026-2030', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Progres Persetujuan'),
  ('PT. MAHAKARYA BAJA ABADI', '2026-2030', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. PUTRA BOMBANA BUANA', '2026-2030', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. BERKAH BERSAMA MINERAL', '2026-2030', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. PEGASING ALAM MAKMUR', '2026-2030', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. ARUL PEGASING MINERAL', '2026-2030', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. ANDALAS ASWINDRA JAYA', '2026-2030', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. SINGKIL KAYA MINERAL', '2026-2030', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. BHUMI KANAKA ARDILAYA', '2026-2030', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. ANDALAS ACEH MINING', '2026-2030', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. ACEH PRIMA GEMILANG', '2026-2030', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum Ada Dokumen RR'),
  ('PT. NAGAN MINERAL MURNI', '2026-2030', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Progres Persetujuan')
)
INSERT INTO public.reklamasi_eks (pemegang_iup, tahun, dokumen, no_sk_pengesahan, jumlah_rencana, no_deposito, nama_bank, jumlah_jaminan, keterangan)
SELECT pemegang_iup, tahun, dokumen, no_sk_pengesahan, jumlah_rencana, no_deposito, nama_bank, jumlah_jaminan, keterangan FROM source s
WHERE NOT EXISTS (
  SELECT 1 FROM public.reklamasi_eks d
  WHERE upper(regexp_replace(d.pemegang_iup, '[^A-Za-z0-9]', '', 'g')) =
        upper(regexp_replace(s.pemegang_iup, '[^A-Za-z0-9]', '', 'g'))
);
-- reklamasi_op: 21 source records; skip a company already represented in this module.
WITH source (pemegang_iup, periode_ke, dokumen, no_sk_pengesahan, jumlah_rencana, no_deposito, nama_bank, jumlah_jaminan, keterangan) AS (VALUES
  ('KOPERASI PUTRA PUTRI ACEH', '2025-2029', 'Ada', NULL, 0, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Progres Evaluasi'),
  ('KSU TIEGA MANGGIS', '2022-2026', 'Tidak', '540/999 & 20 Oktober 2022', 414609110, 'AA 45699', 'BANK ACEH', 414609110, 'Sudah menempatkan jaminan'),
  ('PT. AGRABUDI JASA BERSAMA', '2022-2026', 'Ada', '540/873', 12347657623, 'AA 40490', 'BANK ACEH', 12347567623, 'Sudah menempatkan jaminan'),
  ('PT. BARA ENERGI LESTARI', '2025-2027', 'Ada', '500.10.29.16/1336', 16729005000, 'AB 00056706 / BSI; AB 00056715 / BSI', NULL, 10447605000, 'Sudah menempatkan jaminan; Sampai tahun 2026'),
  ('PT. BUMI BABAHROT', '2022-2026', 'Ada', '500.10.29.16/287', 1220448000, 'AA 87021', 'BANK ACEH', 1220448000, 'Sudah menempatkan jaminan'),
  ('PT. ENERGY TAMBANG GEMILANG', '2025-2029', 'Ada', '500.10.29.16/573', 3665787415, 'AA 78215', 'BANK ACEH', 3665787415, 'Sudah menempatkan jaminan'),
  ('PT. ESTAMO MANDIRI', '2024-2028', 'Ada', '500.10.29/1224 & 04 Oktober 2024', 1806177000, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Sudah persetujuan namun belum menempatkan jaminan'),
  ('PT. INDONESIA PACIFIC ENERGY', '2021-2025', 'Ada', '500.10.29.16/1568', 5760140000, 'AA 78209', 'BANK ACEH', 5760140000, 'Sudah menempatkan jaminan'),
  ('PT. JUYA ACEH MINING', '2023-2027', 'Ada', '500.10.29.16/075', 1825041000, 'AA 78228', 'BANK ACEH', 1825041000, 'Sudah menempatkan jaminan'),
  ('PT. LEUSER KARYA TAMBANG', '2023-2027', 'Ada', '500.10.29.16/039', 528048000, 'AA 484948', 'BANK ACEH', 528048000, 'Sudah menempatkan jaminan'),
  ('PT. LHOONG SETIA MINING', '2026-2030', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum menyampaikan dokumen RR 2026-2030'),
  ('PT. MAGELLANIC GARUDA KENCANA', '2024-2028', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum menyampaikan revisi Dokumen RR'),
  ('PT. MEGA MULTI CEMERLANG', '2023-2027', 'Ada', '500.10.29.16/1575', 3258315000, 'AA 78226', 'BANK ACEH', 3258315000, 'Sudah menempatkan jaminan'),
  ('PT. MIFA BERSAUDARA', '2022-2026', 'Ada', '540/421 & 11 APRIL 2022', 5296900000, 'AA 00003799 / BSI; AB 00056503 / BSI; AB 00056532 / BSI; AB 00056545 / BSI; AB 00056713 / BSI', NULL, 5296900000, 'Sudah menempatkan jaminan'),
  ('PT. NIRMALA COAL NUSANTARA', '2022-2026', 'Ada', '500.10.29.16/105', 11057626000, 'AB 00056725 / BSI; AB 00056724 / BSI; AB 00056722 / BSI; AB 00056723 / BSI; AB 00056726 / BSI', NULL, 11057626000, 'Sudah menempatkan jaminan'),
  ('PT. PEGASUS MINERAL NUSANTARA', '2026-2030', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Proses Evaluasi'),
  ('PT. PIYEUNG MINING', '2024-2028', 'Tidak', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum menyampaikan dokumen RR 2024-2028'),
  ('PT. PRIMA BARA MAHADANA', '2022-2026', 'Ada', '500.10.29.16/855', 1134995000, 'AA 78264', 'Bank Aceh', 1134995000, 'Sudah menempatkan jaminan'),
  ('PT. SAMANA CITRA AGUNG (ABES)', '2024-2028', 'Ada', '500.10.29.16/825', 135670000, 'AA 67959', 'BANK ACEH', 50000000, 'Sudah menempatkan jaminan; Sampai tahun 2025'),
  ('PT. SAMANA CITRA AGUNG (PIDIE)', '2024-2028', 'Ada', '500.10.29.16/826', 171580000, 'AA 67959', 'BANK ACEH', 25000000, 'Sudah menempatkan jaminan; Sampai tahun 2025'),
  ('PT. SURYA MAKMUR INDONESIA', '2025-2029', 'Ada', NULL, NULL, NULL, NULL, NULL, 'Belum Menempatkan Jaminan; Belum menyampaikan revisi')
)
INSERT INTO public.reklamasi_op (pemegang_iup, periode_ke, dokumen, no_sk_pengesahan, jumlah_rencana, no_deposito, nama_bank, jumlah_jaminan, keterangan)
SELECT pemegang_iup, periode_ke, dokumen, no_sk_pengesahan, jumlah_rencana, no_deposito, nama_bank, jumlah_jaminan, keterangan FROM source s
WHERE NOT EXISTS (
  SELECT 1 FROM public.reklamasi_op d
  WHERE upper(regexp_replace(d.pemegang_iup, '[^A-Za-z0-9]', '', 'g')) =
        upper(regexp_replace(s.pemegang_iup, '[^A-Za-z0-9]', '', 'g'))
);
-- Pascatambang: 21 source records.
WITH source (pemegang_iup, no_sk_pengesahan, jumlah_rencana, jumlah_jaminan, status_jaminan) AS (VALUES
  ('KOPERASI PUTRA PUTRI ACEH', NULL, 0, NULL, 'Belum Menempatkan Jaminan dan Dokumen Pascatambang Progres Revisi'),
  ('KSU TIEGA MANGGIS', '540/999', 548752078, 548752078, 'Jaminan Terpenuhi'),
  ('PT. AGRABUDI JASA BERSAMA', '540/874', 6810146000, 6810146000, 'Jaminan Terpenuhi'),
  ('PT. BARA ENERGI LESTARI', '545/535/2014', 4745031258, 3155445785, 'Penempatan Jaminan ke-10'),
  ('PT. BUMI BABAHROT', '540/304', 1169291970, 389374226, 'Penempatan Jaminan ke-1'),
  ('PT. ENERGY TAMBANG GEMILANG', NULL, NULL, NULL, 'Penempatan JamPas dimulai tahun 2028'),
  ('PT. ESTAMO MANDIRI', NULL, NULL, NULL, 'Belum Menempatkan Jaminan'),
  ('PT. INDONESIA PACIFIC ENERGY', NULL, NULL, 2434508168, 'Penempatan Jaminan ke-8'),
  ('PT. JUYA ACEH MINING', NULL, 348500000, 348500000, 'Jaminan Terpenuhi'),
  ('PT. LEUSER KARYA TAMBANG', NULL, NULL, 677281590, NULL),
  ('PT. LHOONG SETIA MINING', '500.10.28/702', 1725563030, 1725563030, 'Jaminan Terpenuhi'),
  ('PT. MAGELLANIC GARUDA KENCANA', '540/148', 826219000, 22308000, 'Penempatan Jaminan ke-1'),
  ('PT. MEGA MULTI CEMERLANG', NULL, NULL, 1567431337, 'Penempatan Jaminan ke-6'),
  ('PT. MIFA BERSAUDARA', NULL, 6718787406, 4528462711, 'Penempatan Jaminan ke-11'),
  ('PT. NIRMALA COAL NUSANTARA', '540/133', 390000000, 390000000, 'Jaminan Terpenuhi'),
  ('PT. PEGASUS MINERAL NUSANTARA', NULL, NULL, NULL, 'Proses Evaluasi Dokumen'),
  ('PT. PIYEUNG MINING', '540/516', 1000000000, NULL, 'Belum Menempatkan Jaminan'),
  ('PT. PRIMA BARA MAHADANA', NULL, NULL, NULL, 'Proses Evaluasi Dokumen'),
  ('PT. SAMANA CITRA AGUNG (ABES)', NULL, 175966500, 175966500, 'Jaminan Terpenuhi'),
  ('PT. SAMANA CITRA AGUNG (PIDIE)', NULL, 121983000, 121983000, 'Jaminan Terpenuhi'),
  ('PT. SURYA MAKMUR INDONESIA', NULL, NULL, NULL, 'Belum Menempatkan Jaminan')
)
INSERT INTO public.pascatambang (pemegang_iup, no_sk_pengesahan, jumlah_rencana, jumlah_jaminan, status_jaminan)
SELECT pemegang_iup, no_sk_pengesahan, jumlah_rencana, jumlah_jaminan, status_jaminan FROM source s
WHERE NOT EXISTS (
  SELECT 1 FROM public.pascatambang d
  WHERE upper(regexp_replace(d.pemegang_iup, '[^A-Za-z0-9]', '', 'g')) =
        upper(regexp_replace(s.pemegang_iup, '[^A-Za-z0-9]', '', 'g'))
);

COMMIT;
